### PR TITLE
QT5.4 migration

### PR DESCRIPTION
**Pull request by habipyesilyurt**
Project ported to Qt5.4  
#127 

I have made changes to clone of "leonardo2d/douml". I cloned it about 6 monts ago and it took so much time. It seems that I have made changes to wrong repo causing conflicts for merging.

### CODE REVIEW

**Comment by habipyesilyurt** [comment]
Hi,
I think it is importent to move Qt5. Is there a problem with my pullrequest. In case requested I can work on it. Can someone inform me how can I contribute to solve the problem?

**Comment by leonardo2d** [comment]
Hi! I agree that it is important to move to Qt5.

I'll try to work on the merge on this weekend, I cannot automatically merge and test what you did, but if you want to try and produce another pull request, you could clone this repository and trying to merge it on the repository you have with your changes. You're going to have conflicts that needs to be solved after the merge before doing another pull request. That's what I'll try, anyways.

**Comment by glixx** [comment]
Hi, will you finish qt5 migration?

**Comment by habipyesilyurt** [comment]
Hi,
I have forked project from "DoUML <https://github.com/DoUML> / douml
<https://github.com/DoUML/douml>". But I can not sync my changes with
github.
I was busy with my work for long time.

I am trying to find a way to sync my changes.




2015-06-30 17:34 GMT+03:00 glixx <notifications@github.com>:

**Comment by mobius3** [comment]
I currently have little time to work on DoUML.
@habipyesilyurt, what is the issue you're having?

**Comment by mobius3** [comment]
I've merged https://github.com/DoUML/douml/pull/135. Can I close this one?

**Comment by habipyesilyurt** [comment]
Although some bugs expected, project can be buitt with qt5.4. So #135 can
be closed.

2015-07-01 2:56 GMT+03:00 Leonardo Guilherme de Freitas <
notifications@github.com>:

**Comment by glixx** [comment]
habipyesilyurt, please check patch https://github.com/DoUML/douml/issues/127

**Pull request closed without merging**
