### PR TITLE
Non latin1 string support is added

### PR DESCRIPTION
**Pull request by habipyesilyurt**
UTF-8 (which covers all the modern characters) is used for saving/reading of project files.

### CODE REVIEW

**Comment by mobius3** [comment]
By useless you mean it does nothing or what it does is not necessary anymore?

**Comment by gilbertoca** [comment]
Hi, I have [sample project](https://github.com/gilbertoca/construtor/tree/master/park-samples) that can be used to test this feature. 
In the [docs folder](https://github.com/gilbertoca/construtor/tree/master/park-samples/docs) there are two sub projects:
bouml.pt_br
bouml

**Comment by habipyesilyurt** [comment]
I think it is not necessary. Usage of codec setting is generally via toUnicode and fromUnicode operations. But QString is holding text as unicode already. So toUnicode and fromUnicode operations should be removed carefully. But it needs a double check :)

**Comment by habipyesilyurt** [comment]
@gilbertoca sample projects seems to be saved using iso8859-1. So, character  "í" is parsed wrongly. If  it would be saved using codec UTF-8, this character would also displayed correctly.

**Comment by gilbertoca** [comment]
Using the 1.0.8 version. 
Set environment to iso8859-1 I can open the project(and see) but can't use the Latin1 characters.
screenshot_20160226_113240
Set environment to UTF-8  I can open the project(see) and change the Latin1 characters. After save, close the project and open it again the Latin1 characters are messy/malformed
screenshot_20160226_114206

**Pull request merged**
